[features]
seeds = false
[programs.localhost]
myepicproject = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localhost"
wallet = "/home/solana-development/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
